name: Deploy to production
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # fetch all commits to get last updated time or other git log info
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
      - name: Pack
        run : |
          npm pack
