name: Deploy to production
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: "16"
      - name: Pack
        run: |
          npm pack
