name: Deploy to production
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Deploy to production
        run: |
          cd /home/smaug/sites/smaug-website/
          ssh -vv git@github.com
          git stash
          git pull origin main
          yarn
          yarn build
          pm2 reload ecosystem.config.js
